
device: "cpu"
batch_size: 2
num_workers: 4

train_path: "/root/MLOps_mipt/examples/train_ptbxll.csv"
valid_path: "/root/MLOps_mipt/examples/train_ptbxll.csv"
test_path: "./example/mlops_example.csv"

checkpoint_path: "."
